In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5,6]
print(a)

[1, 2, 3, 4, 5, 6]


In [10]:
add=np.add(a,b)
print(add)

[[ 6  8]
 [10 12]]


In [11]:
a=np.array([1,2,3,4,5,6])
b=np.array([[9,8,7],[6,5,4]])
print(a)
print(b)

[1 2 3 4 5 6]
[[9 8 7]
 [6 5 4]]


In [12]:
sliced=a[2:]
print(sliced)

[3 4 5 6]


In [13]:
print(a.sum())
print(b.sum())



21
39


In [14]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)
mul=np.dot(a,b)
print(mul)
mulm=np.multiply(a,b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [16]:
subm=np.subtract(a,b)
print(subm)

[[-4 -4]
 [-4 -4]]


In [17]:
m3=np.array([1,2,3,4,5,6,7,8,9])
print(m3)
re=m3.reshape(3,3)
print(re)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print("maximum 3 is ",m3.max())
print("minimum m3 is",m3.min())
print("max row is ",re.max(axis=1))
print("max in col is",re.min(axis=0))

maximum 3 is  9
minimum m3 is 1
max row is  [3 6 9]
max in col is [1 2 3]


In [25]:
m4=np.array([[4,9,25],[36,49,64]])
print(m4)
print(np.sqrt(m4))
print('standered devision :',np.std(m4))

[[ 4  9 25]
 [36 49 64]]
[[2. 3. 5.]
 [6. 7. 8.]]
standered devision : 21.16141667175323


In [31]:
v=np.vstack((a,b))
print(v)
h=np.hstack((a,b))
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [42]:
arr=np.arange(0,20,2,int)
arr2=np.arange(0,20,2,float)
print(arr)
print('data type:',arr.dtype)
print('data type:',arr2.dtype)

[ 0  2  4  6  8 10 12 14 16 18]
data type: int64
data type: float64


In [47]:
arr3=np.linspace(0,20,5)
print(arr3)
print(arr3.dtype)

[ 0.  5. 10. 15. 20.]
float64


In [48]:
ht=h.T
print(ht)

[[1 3]
 [2 4]
 [5 7]
 [6 8]]


In [49]:
for i in np.nditer(ht):
    print(i)

1
2
5
6
3
4
7
8
