In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [5]:
a=np.array([[1,2,3],[5,6,7]])
print(a)

[[1 2 3]
 [5 6 7]]


In [6]:
a=np.array([['harshil','ayush'],['khushi','rutvi']])
print(a)

[['harshil' 'ayush']
 ['khushi' 'rutvi']]


In [7]:
print("shape of a{}".format(a.shape))

shape of a(2, 2)


In [8]:
print("ndim {}".format(a.ndim))

ndim 2


In [11]:
print("size {}".format(a.size))
print(f"dtype {a.dtype}")
print(f"itemsize {a.itemsize}")
print(f"data {a.data}")

size 4
dtype <U7
itemsize 28
data <memory at 0x7f45a408b2b0>
